- name: Fetch RKE2 token from server
  tags: [rke2_node]
  slurp:
    src: /etc/rancher/rke2/rke2-token.txt
  delegate_to: 192.168.0.71
  run_once: true
  register: server_token_file

- name: Set fact with token
  tags: [rke2_node]
  set_fact:
    rke2_token: "{{ server_token_file.content | b64decode }}"

- name: Create RKE2 config directory
  tags: [rke2_node]
  file:
    path: /etc/rancher/rke2
    state: directory

- name: Create config.yaml
  tags: [rke2_node]
  copy:
    dest: /etc/rancher/rke2/config.yaml
    content: |
      server: https://{{ server_ip }}:9345
      write-kubeconfig-mode: "0644"
      token: "{{ rke2_token }}"
      tls-san:
        - "{{ fqdn }}"

- name: Install RKE2 agent
  tags: [rke2_node]
  shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="server" sh -

- name: Enable and start rke2-server
  tags: [rke2_node]
  systemd:
    name: rke2-server
    enabled: yes
    state: started
