# roles/common/tasks/main.yml
- name: Update OS
  tags: [common]
  zypper:
    name: '*'
    state: latest
    update_cache: yes

- name: Disable firewalld
  tags: [common]
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Install common packages
  tags: [common]
  zypper:
    name:
      - open-vm-tools
      - open-iscsi
      - qemu-guest-agent
      - chrony
    state: present

- name: Set timezone to UTC (Etc/UTC)
  timezone:
    name: Etc/UTC
  tags: [common]

- name: Configure NTP servers in chrony.conf
  blockinfile:
    path: /etc/chrony.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      server 0.pool.ntp.org iburst
      server 1.pool.ntp.org iburst
      server 2.pool.ntp.org iburst
      server 3.pool.ntp.org iburst
  tags: [common]

- name: Restart and enable chrony to sync time
  systemd:
    name: chronyd
    enabled: yes
    state: restarted
  tags: [common]

- name: Force time synchronization
  command: chronyc -a makestep
  tags: [common]

- name: Enable Docker
  tags: [common]
  systemd:
    name: docker
    enabled: yes
    state: started

